package model;

import java.util.List;

public record RaceResult(String id, String raceName, String position, int points) {
    public static List<RaceResult> get2024RaceResults() {
        return List.of(
                new RaceResult("1","Bahrain Grand Prix","1",26),
                new RaceResult("11","Bahrain Grand Prix","2",18),
                new RaceResult("55","Bahrain Grand Prix","3",15),
                new RaceResult("16","Bahrain Grand Prix","4",12),
                new RaceResult("63","Bahrain Grand Prix","5",10),
                new RaceResult("1","Saudi Arabian Grand Prix","1",25),
                new RaceResult("11","Saudi Arabian Grand Prix","2",18),
                new RaceResult("16","Saudi Arabian Grand Prix","3",16),
                new RaceResult("81","Saudi Arabian Grand Prix","4",12),
                new RaceResult("14","Saudi Arabian Grand Prix","5",10),
                new RaceResult("38","Saudi Arabian Grand Prix","7",6),
                new RaceResult("55","Australian Grand Prix","1",25),
                new RaceResult("16","Australian Grand Prix","2",19),
                new RaceResult("4","Australian Grand Prix","3",15),
                new RaceResult("81","Australian Grand Prix","4",12),
                new RaceResult("11","Australian Grand Prix","5",10),
                new RaceResult("1","Japanese Grand Prix","1",26),
                new RaceResult("11","Japanese Grand Prix","2",18),
                new RaceResult("55","Japanese Grand Prix","3",15),
                new RaceResult("16","Japanese Grand Prix","4",12),
                new RaceResult("4","Japanese Grand Prix","5",10),
                new RaceResult("1","Chinese Sprint","1",8),
                new RaceResult("44","Chinese Sprint","2",7),
                new RaceResult("11","Chinese Sprint","3",6),
                new RaceResult("16","Chinese Sprint","4",5),
                new RaceResult("55","Chinese Sprint","5",4),
                new RaceResult("1","Chinese Grand Prix","1",25),
                new RaceResult("4","Chinese Grand Prix","2",18),
                new RaceResult("11","Chinese Grand Prix","3",15),
                new RaceResult("16","Chinese Grand Prix","4",12),
                new RaceResult("55","Chinese Grand Prix","5",10),
                new RaceResult("16","Miami Sprint","2",7),
                new RaceResult("55","Miami Sprint","5",4),
                new RaceResult("16","Miami Grand Prix","3",15),
                new RaceResult("55","Miami Grand Prix","5",10),
                new RaceResult("16","Emilia Romagna Grand Prix","3",15),
                new RaceResult("55","Emilia Romagna Grand Prix","5",10),
                new RaceResult("16","Monaco Grand Prix","1",25),
                new RaceResult("55","Monaco Grand Prix","3",15),
                new RaceResult("16","Canadian Grand Prix","Ret",0),
                new RaceResult("55","Canadian Grand Prix","Ret",0),
                new RaceResult("16","Spanish Grand Prix","5",10),
                new RaceResult("55","Spanish Grand Prix","6",8),
                new RaceResult("16","Austrian Sprint","7",2),
                new RaceResult("55","Austrian Sprint","5",4),
                new RaceResult("16","Austrian Grand Prix","11",0),
                new RaceResult("55","Austrian Grand Prix","3",15),
                new RaceResult("16","British Grand Prix","14",0),
                new RaceResult("55","British Grand Prix","5",11),
                new RaceResult("16","Hungarian Grand Prix","4",12),
                new RaceResult("55","Hungarian Grand Prix","6",8),
                new RaceResult("16","Belgian Grand Prix","3",15),
                new RaceResult("55","Belgian Grand Prix","6",8),
                new RaceResult("16","Dutch Grand Prix","3",15),
                new RaceResult("55","Dutch Grand Prix","5",10),
                new RaceResult("16","Italian Grand Prix","1",25),
                new RaceResult("55","Italian Grand Prix","4",12),
                new RaceResult("16","Azerbaijan Grand Prix","2",18),
                new RaceResult("55","Azerbaijan Grand Prix","18",0),
                new RaceResult("16","Singapore Grand Prix","5",10),
                new RaceResult("55","Singapore Grand Prix","7",6),
                new RaceResult("16","United States Sprint","4",5),
                new RaceResult("55","United States Sprint","2",7),
                new RaceResult("16","United States Grand Prix","1",25),
                new RaceResult("55","United States Grand Prix","2",18),
                new RaceResult("16","Mexico City Grand Prix","3",16),
                new RaceResult("55","Mexico City Grand Prix","1",25),
                new RaceResult("16","São Paulo Sprint","3",6),
                new RaceResult("55","São Paulo Sprint","5",4),
                new RaceResult("16","São Paulo Grand Prix","5",10),
                new RaceResult("55","São Paulo Grand Prix","Ret",0),
                new RaceResult("16","Las Vegas Grand Prix","4",12),
                new RaceResult("55","Las Vegas Grand Prix","3",15),
                new RaceResult("16","Qatar Sprint","5",4),
                new RaceResult("55","Qatar Sprint","4",5),
                new RaceResult("16","Qatar Grand Prix","2",18),
                new RaceResult("55","Qatar Grand Prix","6",8),
                new RaceResult("16","Abu Dhabi Grand Prix","3",15),
                new RaceResult("55","Abu Dhabi Grand Prix","2",18)
                );
    }
}
